import Head from "next/head";
import Image from "next/image";
import Img from "../public/img.png";
import List1 from "../public/List1.png";
import List2 from "../public/List2.png";
import List3 from "../public/List3.png";
import Footer from "../pages/footer";
import Header from "../pages/header";
export default function Home() {
  return (
    <div>
      <Head>
        <title> Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col">
          <Header />
        </div>
        <div className="flex lg:flex-row flex-col-reverse lg:px-36 px-2 mt-20 mb-16 place-content-center">
          <div className="flex flex-col flex-wrap" id="work">
            <div className="font-bold text-4xl">
              Hi, I am John,
              <br />
              Creative Technologist
            </div>
            <div className="py-4">
              Amet minim mollit non deserunt ullamco est sit aliqua dolor do
              <br />
              amet sint. Velit officia consequat duis enim velit mollit.
              <br />
              Exercitation veniam consequat sunt nostrud amet.
              <br />
            </div>
            <div>
              <button
                type="button"
                className="bg-red-400 px-4 py-2 text-white font-semibold"
              >
                Download Resume
              </button>
            </div>
          </div>
          <div className="flex flex-wrap">
            <div className="lg:ml-20 lg:mt-2 border-2 border-indigo-300 rounded-full bg-indigo-300">
              <Image src={Img} alt="Portfolio" />
            </div>
          </div>
        </div>
        <div
          id="blog"
          className="bg-blue-300 py-8 px-24 flex flex-col my-2 place-content-center"
        >
          <div>
            <div className="float-left font-medium">Recent posts</div>
            <div className="float-right font-medium text-sky-600">View All</div>
          </div>
          <div className="flex lg:flex-row flex-col mt-2 place-content-center">
            <div className="flex flex-wrap border-2 border-white rounded-md bg-white p-2 m-1">
              <div className="text-3xl font-bold">
                Making a design system from scratch
              </div>
              <div>12 Feb 2020 | Design, Pattern</div>
              <div>
                Amet minim mollit non deserunt ullamco est sit aliqua dolor do
                amet sint. Velit officia consequat duis enim velit mollit.
                Exercitation veniam consequat sunt nostrud amet.
              </div>
            </div>
            <div className="flex flex-wrap border-2 border-white rounded-md  bg-white p-2 m-1">
              <div className="text-3xl font-bold">
                Making a design system from scratch
              </div>
              <div>12 Feb 2020 | Design, Pattern</div>
              <div>
                Amet minim mollit non deserunt ullamco est sit aliqua dolor do
                amet sint. Velit officia consequat duis enim velit mollit.
                Exercitation veniam consequat sunt nostrud amet.
              </div>
            </div>
          </div>
        </div>
        <div className="px-24 flex flex-col" id="contact">
          <div className="text-xl font-md">Featured works</div>
          <div className="flex flex-row mt-2">
            <div>
              <Image src={List1} alt="List" />
            </div>
            <div className="flex flex-col flex-grow-4 ml-4">
              <div className="text-2xl font-bold">Designing Dashboards</div>
              <div className="flex flex-row mt-2">
                <div>
                  <button className="rounded-full text-white px-2 text-center text-xs py-1 bg-black">
                    2020
                  </button>
                </div>
                <div className="text-gray-300 text-semibold ml-6">
                  Dashboard
                </div>
              </div>
              <div className="flex flex-wrap mt-2">
                Amet minim mollit non deserunt ullamco est sit aliqua dolor do
                amet sint. Velit officia consequat duis enim velit mollit.
                Exercitation veniam consequat sunt nostrud amet.
              </div>
            </div>
          </div>
          <div className="h-px bg-gray-300 my-2"></div>
          <div className="flex flex-row mt-2">
            <div>
              <Image src={List2} alt="List" />
            </div>
            <div className="flex flex-col flex-grow-4 ml-4">
              <div className="text-2xl font-bold">
                Vibrant Portraits of 2020
              </div>
              <div className="flex flex-row mt-2">
                <div>
                  <button className="rounded-full text-white px-2 text-center text-xs py-1 bg-black">
                    2020
                  </button>
                </div>
                <div className="text-gray-300 text-semibold ml-6">
                  Dashboard
                </div>
              </div>
              <div className="flex flex-wrap mt-2">
                Amet minim mollit non deserunt ullamco est sit aliqua dolor do
                amet sint. Velit officia consequat duis enim velit mollit.
                Exercitation veniam consequat sunt nostrud amet.
              </div>
            </div>
          </div>
          <div className="h-px bg-gray-300 my-2"></div>
          <div className="flex flex-row mt-2">
            <div>
              <Image src={List3} alt="List" />
            </div>
            <div className="flex flex-col flex-grow-4 ml-4">
              <div className="text-2xl font-bold">
                36 Days of Malayalam type
              </div>
              <div className="flex flex-row mt-2">
                <div>
                  <button className="rounded-full text-white px-2 text-center text-xs py-1 bg-black">
                    2020
                  </button>
                </div>
                <div className="text-gray-300 text-semibold ml-6">
                  Dashboard
                </div>
              </div>
              <div className="flex flex-wrap mt-2">
                Amet minim mollit non deserunt ullamco est sit aliqua dolor do
                amet sint. Velit officia consequat duis enim velit mollit.
                Exercitation veniam consequat sunt nostrud amet.
              </div>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
